import 'package:cloud_firestore/cloud_firestore.dart';

import '../../domain/entities/delivery_address.dart';

/// Handles all Firestore CRUD operations for the `/users/{uid}/addresses`
/// subcollection.
///
/// Accepts an optional [FirebaseFirestore] instance for testability;
/// defaults to [FirebaseFirestore.instance] in production.
class FirestoreAddressDataSource {
  FirestoreAddressDataSource({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  final FirebaseFirestore _firestore;

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  CollectionReference<Map<String, dynamic>> _addressesCollection(String uid) =>
      _firestore.collection('users').doc(uid).collection('addresses');

  DocumentReference<Map<String, dynamic>> _addressDoc(
    String uid,
    String addressId,
  ) =>
      _addressesCollection(uid).doc(addressId);

  // ---------------------------------------------------------------------------
  // Read
  // ---------------------------------------------------------------------------

  /// Returns all [DeliveryAddress] records for [uid].
  ///
  /// Sorted in Dart: default address first, then remaining addresses by
  /// [DeliveryAddress.createdAt] ascending.
  Future<List<DeliveryAddress>> getAddresses(String uid) async {
    final snapshot = await _addressesCollection(uid).get();

    final addresses = snapshot.docs.map((doc) {
      final data = <String, dynamic>{'id': doc.id, 'uid': uid, ...doc.data()};
      return DeliveryAddress.fromMap(data);
    }).toList();

    // Sort: default first, then by createdAt ascending.
    addresses.sort((a, b) {
      if (a.isDefault && !b.isDefault) return -1;
      if (!a.isDefault && b.isDefault) return 1;
      return a.createdAt.compareTo(b.createdAt);
    });

    return addresses;
  }

  // ---------------------------------------------------------------------------
  // Create
  // ---------------------------------------------------------------------------

  /// Adds a new address document with an auto-generated ID.
  ///
  /// Enforces a maximum of 10 addresses per user. Throws a [StateError] if
  /// the limit has already been reached.
  ///
  /// Sets `createdAt` to [FieldValue.serverTimestamp()] on write.
  /// Returns the saved [DeliveryAddress] with the generated document ID.
  Future<DeliveryAddress> addAddress(DeliveryAddress address) async {
    // Enforce the 10-address limit before writing.
    final existing = await _addressesCollection(address.uid).count().get();
    final count = existing.count ?? 0;
    if (count >= 10) {
      throw StateError(
        'Address limit reached: uid=${address.uid} already has $count addresses '
        '(maximum is 10).',
      );
    }

    final data = address.toMap()
      ..remove('id') // auto-generated by Firestore
      ..remove('uid') // structural — encoded in the path
      ..remove('createdAt'); // replaced by server timestamp

    final docRef = await _addressesCollection(address.uid).add(<String, dynamic>{
      ...data,
      'createdAt': FieldValue.serverTimestamp(),
    });

    // Return the entity with the generated doc ID and a local createdAt
    // approximation. Callers that need the exact server timestamp should
    // call getAddresses() after this method.
    return address.copyWith(
      id: docRef.id,
      createdAt: DateTime.now(),
    );
  }

  // ---------------------------------------------------------------------------
  // Update
  // ---------------------------------------------------------------------------

  /// Updates an existing address document identified by [address.id].
  ///
  /// Throws a [StateError] if the document does not exist.
  /// Returns the updated [DeliveryAddress].
  Future<DeliveryAddress> updateAddress(DeliveryAddress address) async {
    final ref = _addressDoc(address.uid, address.id);

    final snapshot = await ref.get();
    if (!snapshot.exists) {
      throw StateError(
        'Address document not found: uid=${address.uid}, id=${address.id}',
      );
    }

    final data = address.toMap()
      ..remove('id') // structural — encoded in the path
      ..remove('uid'); // structural — encoded in the path

    await ref.update(data);

    return address;
  }

  // ---------------------------------------------------------------------------
  // Delete
  // ---------------------------------------------------------------------------

  /// Permanently deletes the address document identified by [addressId].
  ///
  /// Throws a [StateError] if the document does not exist.
  Future<void> deleteAddress(String uid, String addressId) async {
    final ref = _addressDoc(uid, addressId);

    final snapshot = await ref.get();
    if (!snapshot.exists) {
      throw StateError(
        'Address document not found: uid=$uid, id=$addressId',
      );
    }

    await ref.delete();
  }

  // ---------------------------------------------------------------------------
  // Set default
  // ---------------------------------------------------------------------------

  /// Atomically sets `isDefault=true` on [addressId] and `isDefault=false`
  /// on all other addresses for [uid].
  ///
  /// Uses a Firestore batch write for atomicity.
  /// Throws a [StateError] if [addressId] does not exist.
  Future<void> setDefaultAddress(String uid, String addressId) async {
    // Verify the target address exists before touching anything.
    final targetRef = _addressDoc(uid, addressId);
    final targetSnapshot = await targetRef.get();
    if (!targetSnapshot.exists) {
      throw StateError(
        'Address document not found: uid=$uid, id=$addressId',
      );
    }

    // Fetch all addresses to build the batch.
    final allSnapshot = await _addressesCollection(uid).get();

    final batch = _firestore.batch();

    for (final doc in allSnapshot.docs) {
      if (doc.id == addressId) {
        batch.update(doc.reference, {'isDefault': true});
      } else {
        batch.update(doc.reference, {'isDefault': false});
      }
    }

    await batch.commit();
  }
}
