definitions:
  scripts:
    - &flutter_get
      name: Get dependencies
      script: flutter pub get
      working_directory: akka_food

workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - *flutter_get
      - name: Install CocoaPods
        script: pod install
        working_directory: akka_food/ios
      - name: Build iOS
        script: flutter build ios --debug --no-codesign
        working_directory: akka_food
    artifacts:
      - akka_food/build/ios/iphoneos/*.app

  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - *flutter_get
      - name: Build APK
        script: flutter build apk --debug
        working_directory: akka_food
    artifacts:
      - akka_food/build/**/outputs/**/*.apk
